### ISSUE TITLE
translationJSON?.Translations?.flowDefinitions?.forEach is not a function

### ISSUE THREAD

**Issue by pfrandsen** [scolladon/sfdx-git-delta#342]
## What is the problem?

---

After upgrading to 5.4.1 we get "translationJSON?.Translations?.flowDefinitions?.forEach" is not a function error. 

delta.json contains:

{
  "error": "translationJSON?.Translations?.flowDefinitions?.forEach is not a function",
  "output": "changes",
  "success": false,
  "warnings": []
}

### What is the expected result?

Same as 5.3.1 - i.e., no error :-)

## Steps to reproduce

---

upgrade to 5.4.1 and run delta

Reverting back to 5.3.1 resolves the issue

## Execution context

---

**Operating System:** 
Windows 10

**yarn version:**
1.12.1

**node version:** …
v16.17.0

**git version:**
git version 2.34.0.windows.1

**sfdx version:**
sfdx-cli/7.163.0 win32-x64 node-v16.16.0

**sgd plugin version:**
@salesforce/sfdx-diff 0.0.6
sfdx-git-delta 5.4.1

**Comment by scolladon** [comment]
Hi @pfrandsen 

Thanks for reporting this, great findings ! 

It is definitely a miss in our integration tests.
I fix it and add some tests to avoid regression.

Thanks for your help making the plugin better
Stay tuned

**Comment by scolladon** [comment]
New version [5.4.2](https://www.npmjs.com/package/sfdx-git-delta) with the fix is just released !

**Comment by pfrandsen** [comment]
Hi Sebastien/@scolladon - thanx for the quick fix - you are doing amazing work 👍 (and sorry for the double reporting by me and a collogue).

I have tested the new version and it works - thanx!

I have run into the same issue when parsing XML with fast-xml-parser - I do not know if it work looking into the "isArray" configuration option, see https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#isarray

Kind Regards
/Peter

**Comment by scolladon** [comment]
Hi @pfrandsen !

Thank you that means a lot.
No worries for the double reporting, I think it is cool to see all the energy from this plugin community, I don't mind duplicate issues :) 

I have been looking into the `isArray` method for this issue and tried a solution using it but I was not very happy with the way I managed to inject it the known attributes that should always behave as an array. I don't want to hard code a list and would like to be able to dynamically set it.
As the point was just to fix the issue fast, I used the same logic done in `inFileHandler` and refactored to create the `asArray` helper.
Next feature (scoping translations and permissions) will also need that, I will have plenty of time to design something I like more using the `isArray` hook as you mentioned.

Thanks for opening the discussion on that! Really helpful
If you want to discuss software design of the plugin and share ideas, [do not hesitate](https://github.com/scolladon/sfdx-git-delta/discussions) !!
